# Generated by Django 4.0.2 on 2022-06-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='repcontraseña',
            field=models.CharField(default='', max_length=100, verbose_name='Repetir contraseña'),
        ),
    ]
