# Generated by Django 4.0.4 on 2022-06-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_repcontraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='envio',
            name='region',
            field=models.IntegerField(blank=True, choices=[[15, 'Arica y Parinacota'], [1, 'Tarapacá'], [2, 'Antofagasta'], [3, 'Atacama'], [4, 'Coquimbo'], [5, 'Valparaíso'], [13, 'Metropolitana de Santiago'], [6, "Del libertador Gral. Bernardo O'Higgins"], [7, 'Del Maule'], [8, 'Del BioBío'], [9, 'De la Araucanía'], [14, 'De los Ríos'], [10, 'De los Lagos'], [11, 'Aysén del Gral. Carlos Ibáñez del Campo'], [12, 'Magallanes y de la Antártica Chilena'], [16, 'Ñuble']], max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna'),
        ),
    ]
